name: Deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: 69.164.241.19
          username: slqnt
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            export PATH=$PATH:/usr/local/bin:/usr/bin:$HOME/.bun/bin:$HOME/.nvm/versions/node/$(ls $HOME/.nvm/versions/node | tail -1)/bin
            cd ~/quasar
            git pull
            bun install
            bun run build:selfhosted
            pm2 restart quasar
